### ISSUE TITLE
Magresview fails to read files containing >100 atoms of a single species

### ISSUE THREAD

**Issue by ThatPerson** [stur86/magresview-2#6]
(this is a duplicate of https://github.com/stur86/crystvis-js/issues/26 as I identified this bug in Magresview 2)

When loading a Magres file with >100 atoms sometimes the ^ms lines can end up formatted like

```
ms H100          2.0431056083497484E+01         -5.5892879764485039E+00          1.2418129913251554E+00         -4.0897852040395684E+00          2.9708843218858465E+01         -3.8875121992744055E+00         -1.1586267278454099E+00          5.0678781904684089E-01          2.4711193494436703E+01
```

In this case, when crystvis-js reads the ms file it will find only 8 elements, and so throw an error like:

```Error parsing file APX_NMR: Input matrix is not symmetric ```

**Comment by stur86** [comment]
Closed here as it's being dealt with in stur86/crystvis-js.
