### ISSUE TITLE
screenshot icon in day mode hard to read

### ISSUE THREAD

**Issue by jryates** [stur86/magresview-2#7]
When I switch from the night to day mode the screenshot icon appears to vanish - it doesn't, it is just very hard to see (Safari 15.0)
<img width="1310" alt="magresview_sh" src="https://user-images.githubusercontent.com/19984219/154866778-3ddaa156-6c56-4e1a-a9ab-626477446a8c.png">

**Comment by stur86** [comment]
Fixed in https://github.com/stur86/magresview-2/commit/c7d0e30f8611edfb01ba985a049341af942df3b6, it should be up in a few minutes.
